AWSTemplateFormatVersion: '2010-09-09'
Description: Books API ECR Repository

Parameters:
  AssumedRole:
    Type: String
    Default: Dev

Resources:
  BooksApiEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AWS::StackName}

Outputs:
  RepositoryARN:
    Value: !GetAtt "BooksApiEcrRepo.Arn"
    Export:
        Name: 'BooksApiRepoArn'
  RepositoryURI:
    Value: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ "/", [ "amazonaws.com", !Ref "AWS::StackName" ] ] ] ]
    Export:
        Name: "BooksApiRepoURI"
